### ISSUE TITLE
Knack Custom Map Interface Discovery

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-knack-data-tracker#139]

**Comment by mateoclarke** [comment]
@sergiogcx, @mddilley and I talked through this and whiteboarded it yesterday. For this problem and in order to get a proof-of-concept working by Monday, we decided to try to create a button in Knack that opens up a separate React app. 

The React app will use a component that the Office of Design & Delivery already made that has the functionality we want with the draggable map. 
https://forms.austin.gov/police-complain/where-happened

Ideally, once a user drags the pin to the precise location, it could submit that lat/lon data to a Knack field via the API and then redirect back to the normal Knack form. The edit process needs a bit more scooping and might not be possible without just deleting and creating a new pin. tdb

We'll be working on that in this repo:
https://github.com/cityofaustin/atd-geospatial-knack-ui

![IMG_7182](https://user-images.githubusercontent.com/5697474/59450235-6348b700-8dce-11e9-82c2-7bc90f99e257.jpg)

**Comment by johnclary** [comment]
have decided to push on with the custom map interface that mateo and mike started, and we'll table fulcrum for now. after running tests in fulcrum on android, it's fine, but not great. not enough to warrant a mad dash to implement it, when we haven't event tested the prototype with end-users...we can revisit mobile solution down the road and ideally solve with knack-react.
