### ISSUE TITLE
Due Date notification on Aging Report items (TMC>Aging Report)

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-data-tracker#158]
Jared 
AMD

Aging Report page: http://transportation.austintexas.io/data-tracker/#home/tmc/aging-report/?view_2354_page=1

1 day notification before `Due_Date` to notify the Signal Engineer based on Area and Status "Pending Engineer Review". 

Ex. Issue is in "Pending Engineer Review" due tomorrow. Notification goes out to the appropriate engineer is the issue is in their engineer area. 

Preferred due date: 2 months from 7/1/19

**Comment by dianamartin** [comment]
@wchIV @johnclary You can probably work on this.

- [ ] Need to create a new field `ONE_DAY_NOTIFY` on `tmc_issues` object table
- [ ] Create task to send out email 

### Reference
[7 day due date alert #100](https://github.com/cityofaustin/atd-knack-data-tracker/issues/100)

**Comment by dianamartin** [comment]
Billy and I just caught up to go over the approach for this enhancement, he'll do the enhancement in TEST to see what works. We could filter by Engineer Area/Status through the task or we may have to create separate filters. He'll send himself emails during testing before we code the engineer emails in there.

**Comment by wchIV** [comment]
I've done a bit of work on this now, and it looks like this should work if we make a separate task for each signal engineer area.  It's not perfect, but since at the moment we only have 5 areas to worry about, it should be all right.   I'll have to figure out some way to test this out, because I'm not sure if the test data tracker will let me e-mail anyone, even myself.  I also need to make sure my equation (ONE_DAY_NOTIFY) and the ONE_DAY_NOTIFY_DATE, which has a conditional rule where if ONE_DAY_NOTIFY is not blank, it sets itself to the date in ONE_DAY_NOTIFY, work.  I'm working on these things now.

**Comment by dianamartin** [comment]
@wchIV The test environment will email out to whoever you put in the email field. It's a test environment in the sense where we mirrored Production, not in the sense that functionality has been disabled.

**Comment by amenity** [comment]
@dianamartin is going to check in with @wchIV about the status of this.

**Comment by amenity** [comment]
@wchIV, would you please write an update to this issue in the comments here?

**Comment by dianamartin** [comment]
@johnclary @amenity 

Met with Billy this afternoon to see what the status of this task. I was able to review the tasks that create the email notifications. He's updated them in the Production environment, but bc we have an issue with the `DUE DATE` field. This will work if this field is populated. I'll wait to let the Signal Engineers know that this functionality exists. 

Right now it's configured with my email, I wanted to see what the notifications look like as a final QA/QC before closing this.
