### ISSUE TITLE
Signal Work Orders: Enforce Correct Time Log Sequencing

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-knack-data-tracker#19]
On signal work orders It's currently possible to submit a "time log entry" with the received, arrived, and/or departure times not in chronological order. We need to enforce that received < arrived < departure < return to shop times are in chronological order.

This may require custom javascript. @dianamartin will you take a look and see if you can solve with field roles and ping @mateoclarke if you need his help on this?

**Comment by dianamartin** [comment]
Tried to troubleshoot and attempt to resolve this. I'm not sure if I'm approaching it correctly. I've tried to make integer/boolean fields, but it doesn't prevent the user from entering the incorrect information. I tried conditional rules on the actual field, validation. We could try to update the existing message that prevents it to be submitted due to lack of time logs. @johnclary I think we might need a work session to truly figure this out. I think I'm close, but not there yet.
