### ISSUE TITLE
Filter technician and support technician fields for active technicians only

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-knack-data-tracker#20]
Check the primary technician and support technician fields on these forms and make sure they are set to filter for active technician users only:

- New Work Order
- Edit Work Order
- anywhere else?

**Comment by johnclary** [comment]
@dianamartin this affects the mobile app so please check this in Mateo's test environment as well.

**Comment by dianamartin** [comment]
I had an SR about this that I had completed. This issue is to check all forms on all environments:

Check the following environments:
`TEST`
- [ ] New Work Order
- [ ] Edit Work Order
- [ ] New Mobile Work Order
- [ ] Edit Mobile Work Order
`PRODUCTION`
- [ ] New Work Order
- [ ] Edit Work Order
- [ ] New Mobile Work Order
- [ ] Edit Mobile Work Order

**Comment by dianamartin** [comment]
Updated all forms in Test and Production environments.
